[versions]
android-compileSdk = "34"
android-minSdk = "25"
android-targetSdk = "34"
project-version-code = "1"
project-version-name = "1.0.0"
kotlin-compiler-extension = "1.5.10"

agp = "8.1.4"
kotlin = "1.9.22"
google-service = "4.4.1"
androidx-activity-compose = "1.8.2"
androidx-browser = "1.8.0"
androidx-compose-mateirla3 = "1.2.1"
androidx-core-ktx = "1.12.0"
androidx-navigation-compose = "2.7.7"
androidx-paging = "3.2.1"
androidx-compose-bom = "2024.03.00"
androidx-datastore = "1.0.0"
compose = "1.6.4"
firebase-crashlytics = "2.9.9"
coil = "2.6.0"
okhttp = "4.12.0"
retrofit = "2.9.0"
material = "1.11.0"
oss-licenses = "17.0.1"
oss-licenses-plugin = "0.10.6"
firebase-bom = "32.8.0"
permissions = "0.30.1"
junit = "4.13.2"
compose-junit = "1.6.4"
esspresso = "3.5.1"
junit-test = "1.1.5"
kotlin-bom = "1.9.20"
coroutine = "1.8.0"
ktlint = "11.5.1"
jetbrainsKotlinJvm = "1.9.22"
orbit = "7.0.1"
room = "2.6.1"
webkit = "1.10.0"
ktxml = "0.2.3"
m3color = "2024.1"
ktor = "2.3.11"
kotlinx = "1.6.2"
androidx-navigation = "2.7.0-alpha03"
androidx-lifecycle = "2.8.0-rc01"
koin = "3.5.3"
sqldelight = "2.0.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-mateirla3" }
androidx-compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "androidx-compose-mateirla3" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-androidx-navigation = { module = "io.insert-koin:koin-androidx-navigation", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
ktxml = { module = "org.kobjects.ktxml:core", version.ref = "ktxml" }
m3color = { module = "com.github.Kyant0:m3color", version.ref = "m3color" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
orbit-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "oss-licenses" }
oss-licenses-plugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "oss-licenses-plugin" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "permissions" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin-bom" }
coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-kotlinx-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }

compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-junit" }
esspresso = { module = "androidx.test.espresso:espresso-core", version.ref = "esspresso" }
junit-test = { module = "androidx.test.ext:junit", version.ref = "junit-test" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics"}
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-service" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
koreatechboard-compose = { id = "com.kongjak.koreatechboard.plugin.compose", version = "unspecified" }
koreatechboard-application = { id = "com.kongjak.koreatechboard.plugin.application", version = "unspecified" }
koreatechboard-library = { id = "com.kongjak.koreatechboard.plugin.library", version = "unspecified" }
koreatechboard-firebase = { id = "com.kongjak.koreatechboard.plugin.firebase", version = "unspecified" }

[bundles]
androidx-compose = [
    "androidx-activity-compose", "androidx-compose-material3", "androidx-compose-material3-window-size", "androidx-compose-runtime-livedata",
    "androidx-compose-ui", "androidx-compose-ui-tooling-preview", "androidx-compose-ui-graphics"
]
