package com.kongjak.koreatechboard.util

enum class HtmlTags(val tag: String, val isBlock: Boolean) {
    DIV("div", true),
    P("p", true),
    H1("h1", true),
    H2("h2", true),
    H3("h3", true),
    H4("h4", true),
    H5("h5", true),
    H6("h6", true),
    BR("br", false),
    HR("hr", false),
    A("a", false),
    SPAN("span", false),
    IMG("img", false),
    TABLE("table", true),
    THEAD("thead", true),
    TBODY("tbody", true),
    TR("tr", true),
    TH("th", true),
    TD("td", true),
    UL("ul", true),
    OL("ol", true),
    LI("li", true),
    B("b", false),
    U("u", false),
    S("s", false),
    STRONG("strong", false),
    EM("em", false),
    DEL("del", false),
    INS("ins", false),
    SUB("sub", false),
    SUP("sup", false),
    STRIKE("strike", false),
    FONT("font", false)
}
